# Seminar 2

## warmup exercise

Given an array of integers nums and an integer target, return indices of the two numbers such that they add up to target.

You may assume that each input would have exactly one solution, and you may not use the same element twice.

You can return the answer in any order.

In [ ]:
#example
arr = [1,2,3,4,5]
# target is 3
# indices are 0,1

In [21]:
def solution(vec=[2,1,5,3],target=4):
    #iterate through input array
    for idx, item in enumerate(vec):
        next_value = target - item
        look_here = vec[idx+1:]
        print(f'we have {item} at indx {idx}. Now look for {next_value} in {look_here}')

        try:
            idx2 = look_here.index(next_value)
            return idx, idx2+idx+1
            
        except ValueError:
            print(f'{next_value} not found')
        
        
    
    
        print(idx, item)
solution()

we have 2 at indx 0. Now look for 2 in [1, 5, 3]
2 not found
0 2
we have 1 at indx 1. Now look for 3 in [5, 3]


(1, 3)

ok


In [22]:
import numpy as np

# numpy recap

In [42]:

odd_arr

array([ 1,  3,  5,  7,  9, 11, 13])

In [47]:
even_arr

array([ 0,  2,  4,  6,  8, 10, 12, 14])

In [66]:
matrix=np.matrix([odd_arr, even_arr])

In [70]:
large_matrix=matrix.T.dot(matrix)

In [78]:
(large_matrix-large_matrix.mean())/(large_matrix.std())

matrix([[-1.05763971, -1.03875328, -1.01986686, -1.00098044, -0.98209401,
         -0.96320759, -0.94432117, -0.92543474],
        [-1.03875328, -0.94432117, -0.84988905, -0.75545693, -0.66102482,
         -0.5665927 , -0.47216058, -0.37772847],
        [-1.01986686, -0.84988905, -0.67991124, -0.50993343, -0.33995562,
         -0.16997781,  0.        ,  0.16997781],
        [-1.00098044, -0.75545693, -0.50993343, -0.26440993, -0.01888642,
          0.22663708,  0.47216058,  0.71768409],
        [-0.98209401, -0.66102482, -0.33995562, -0.01888642,  0.30218277,
          0.62325197,  0.94432117,  1.26539036],
        [-0.96320759, -0.5665927 , -0.16997781,  0.22663708,  0.62325197,
          1.01986686,  1.41648175,  1.81309664],
        [-0.94432117, -0.47216058,  0.        ,  0.47216058,  0.94432117,
          1.41648175,  1.88864233,  2.36080292],
        [-0.92543474, -0.37772847,  0.16997781,  0.71768409,  1.26539036,
          1.81309664,  2.36080292,  2.90850919]])

In [80]:
m = large_matrix.flatten()

In [99]:
is_monotonous(np.arange(34))

TypeError: is_monotonous() takes 0 positional arguments but 1 was given

In [97]:
# Create a simple array of values from 0 to 14
a = np.arange(16)

# Using the same object, subset only odd values - make a new object
odd_arr = a[a%2==1].copy()
# Using the original object, subset only even values - make a new object
even_arr = a[a%2==0].copy()
# Create a matrix with 2 rows with odd values in first row
    # Do you need to make any adjustments?
matrix = np.stack([odd_arr, even_arr])    

# what is the shape of the matrix?
print(matrix.shape)

# what is the sum of the second column?
    # slicing / subsetting

print(matrix[:,1].sum())
# sum the first, third and fith column
print(matrix[:,0:5:2].sum(axis=0))
# multiply the matrix with itself - create 8 x 8 resulting matrix
    #A, B, A-> m x n, B-> n x o => m x o
large_matrix=matrix.T.dot(matrix)

# what is largest elemtn of the matrix? On what index (position) ?

# normalize this matrix (subract mean and divide by sd)
norm_matrix = (large_matrix-large_matrix.mean())/(large_matix.std())

# make this 8x8 matrix into a single vector - save this object! 

# check if the resulting vector is monotonous
    # write a function that returs true of false
    # is it goin up always?
        # look at 1st, see if 2nd is higher
        # 2dn, if 3rd higher

def is_monotonous(m):
    return (np.diff(m)>=0).all() or (np.diff(m)<=0).all()


# how many items is smaller than 100?

# replace the largest value with its double

# simulate data from normal distribution with those mean/sd parameters

# Back to the long vector - replace all values which are less than 50 with -1

# count exactly how many -1s are there

# sort the array
    # check if it is monotonous with your function
    # in a separate cell, measure how long the execution takes
    
    
    
# Bonus task:
# Create a 2d array of size 10x10 with 1 on the border and 0 inside





(2, 8)
5
[ 1  9 17]


NameError: name 'large_matix' is not defined

In [ ]:

# %%timeit

# is_monotonous(np.sort(flat_vec))

# Pandas - Kaggle houses dataset

In [ ]:
# lets try some real world problem
# It is your job to predict the sales price for each house. For each Id in the test set, you must predict the value of the SalePrice variable. 

# Ask a home buyer to describe their dream house, and they probably won't begin with the height of the basement ceiling or the proximity to an east-west railroad. 
# But this playground competition's dataset proves that much more influences price negotiations than the number of bedrooms or a white-picket fence.

# With 79 explanatory variables describing (almost) every aspect of residential homes in Ames, Iowa, this competition challenges you to predict the final price of each home.

# https://www.kaggle.com/c/house-prices-advanced-regression-techniques/overview

# data downloadable from https://soulution-public.s3.amazonaws.com/pythonies/house-prices-advanced-regression-techniques.zip

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats


%matplotlib inline
#https://seaborn.pydata.org/introduction.html

In [ ]:
#load the train data and print columns

# describe the target variable SalePrice




In [ ]:
# check skewness and kurtosis of SalePrice - is it normally distributed?
   # normal dist is 0, 0 


In [ ]:
# create distribution plot of the sale price - comment on it



In [ ]:
#create q-q plot


In [ ]:
# GrLivArea: Above grade (ground) living area square feet
# TotalBsmtSF: Total square feet of basement area
# YearBuilt: Original construction date
# OverallQual: Overall material and finish quality

In [ ]:
#scatter plot grlivarea/saleprice

#scatter plot totalbsmtsf/saleprice

#box plot overallqual/saleprice

# what is the time dynamics of Sale price

# create correlation matrix of all variables - seaborn heatmap

# find the variables most correlated with SalePrice 

# for important variables cols = ['SalePrice', 'OverallQual', 'GrLivArea', 'GarageCars', 'TotalBsmtSF', 'FullBath', 'YearBuilt']
# see if we can create a plot of relationship between all the variables


In [ ]:
# Lets have a look at missing data
# how many missing data has each column?
# what is the percentage? 

# how would you handle this?

# is this dataset prepared for the submission?

#homework; try to make a submission

In [ ]:
#saleprice correlation matrix
#box plot overallqual/saleprice
#saleprice correlation matrix



In [ ]:
#scatterplot

